# Generated by Django 4.2.2 on 2023-06-19 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetaInfo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='WebsiteSetting',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
