# Generated by Django 4.2.1 on 2023-05-11 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metainfo',
            options={'verbose_name': 'Meta Info', 'verbose_name_plural': 'Meta Infos'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='websitesetting',
            options={'verbose_name': 'Website Setting', 'verbose_name_plural': 'Website Settings'},
        ),
    ]
