# Generated by Django 4.2.2 on 2023-06-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20230616_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='username',
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
